language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules #Cache node_modules for faster builds
script:
  - npm run coverage #Runs Tests
  - npm run build #Creats a production build
  after_script: # Upload coverage reports 
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls